### ISSUE TITLE
Latest release does not contain latest merged pull request

### ISSUE THREAD

**Issue by tomsabin** [nickjj/ansible-pumacorn#2]
As shown in https://github.com/nickjj/ansible-pumacorn/compare/v0.1.3...master, the most recent release does not contain the most recent merged pull request

**Comment by nickjj** [comment]
Thanks. `v0.1.4` is out and up on the Galaxy with the latest master progress.

Also I'd strongly consider checking out:
https://github.com/debops/ansible-rails_deploy

If you're using my rails role, the above rails role is the direct successor to it.
